---
# tasks file for prepare_ansible_backup_node

- name: Ensure package dependencies are installed
  package:
    name:
      - vim
      - diffutils
      - sshpass
      - traceroute
      - python3-lxml
    state: present
  delegate_to: localhost
  become: true

- name: Create {{ current_date }} folders for configs
  file:
    path: /ansible_backups/{{ item }}/{{ current_date }}
    state: directory
    mode: 0775
    owner: awx
    group: awx
  with_items: "{{ platforms }}"
  become: True

- name: Create {{ current_date }} folders for diffs
  file:
    path: /ansible_backups/{{ item }}_diffs/{{ current_date }}
    state: directory
    mode: 0775
    owner: awx
    group: awx
  with_items: "{{ platforms }}"
  become: True
